name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      push: ${{ github.repository_owner == 'wpilibsuite' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          version: v0.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.repository_owner == 'wpilibsuite' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Base
      - name: Test Base - Docker meta
        id: test_base_docker_meta
        uses: docker/metadata-action@v3
        with:
          images: wpilib/axon-test-base
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=edge
            type=semver,pattern={{version}}
      - name: Base - Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ env.push }}
          load: ${{ !env.push }}
          file: /Dockerfile
          tags: ${{ steps.test_base_docker_meta.outputs.tags }}
          labels: ${{ steps.test_base_docker_meta.outputs.labels }}
